In [1]:
#Install Packages
import pandas as pd

#Load in data
air_data = pd.read_csv('AirQuality_Daily_StudentVersion.csv')

#Put data in a dataframe
air_data = pd.DataFrame(air_data)

#Check that data is properly loaded
print(air_data)

          date  monitor_index   humidity    pressure  temperature         voc  \
0     02/23/24         195089  14.377667  912.884333    62.266667   51.998667
1     02/23/24         195365  12.223600  926.403000    71.193400   64.920800
2     02/23/24         195541  20.095750  905.670750    61.008250   68.307000
3     02/24/24         195089  25.368000  911.708833    51.462458   91.176750
4     02/24/24         195365  23.703083  925.282125    56.818208  107.863708
...        ...            ...        ...         ...          ...         ...
8296  03/24/25         195373  23.636208  915.998292    61.489083  421.493750
8297  03/24/25         195379  28.043545  954.294546    66.009182  301.074800
8298  03/24/25         195383  31.451375  936.556583    55.752792  353.478000
8299  03/24/25         195385        NaN         NaN          NaN         NaN
8300  03/24/25         195541  20.494500  901.484750    61.222167  485.556417

      analog_input  pm2.5_alt  pm1.0_atm  pm2.5_atm  pm10.0_atm  \
0         0.051333   0.100000   0.000000   0.002500    0.039667
1         0.000000   0.180000   0.004800   0.020000    0.176000
2         0.020000   0.162500   0.004125   0.014812    0.063937
3         0.052667   0.437500   0.099542   0.170667    0.355208
4         0.000000   0.475000   0.099208   0.231687    0.548583
...            ...        ...        ...        ...         ...
8296      0.020000   0.762500   0.486583   0.830021    1.416125
8297      0.000000   0.800000   5.625545   5.873364    6.056773
8298      0.050000   0.575000   0.267500   0.478375    0.818146
8299      0.010000   0.970833   0.739500   1.088604    1.340563
8300      0.020000   0.554167   0.132083   0.340417    0.737375

      sensor.latitude  sensor.longitude  sensor.altitude  \
0           40.050922       -101.533570             3005
1           40.200330       -100.639885             2576
2           41.128284       -101.720220             3220
3           40.050922       -101.533570             3005
4           40.200330       -100.639885             2576
...               ...               ...              ...
8296        41.148170       -100.761800             2800
8297        40.877007        -97.579445             1639
8298        41.779380        -99.138040             2174
8299        40.019714        -98.071840             1597
8300        41.128284       -101.720220             3220

                                            sensor.name
0                                      Swnphd-Benklemen
1                                         Swnphd-mccook
2                                       Swnphd-ogallala
3                                      Swnphd-Benklemen
4                                         Swnphd-mccook
...                                                 ...
8296                                WCDHD City Building
8297                                           FCHD-YPS
8298                Loup Basin Public Health Department
8299  South Heartland District Health Dept. Superior...
8300                                    Swnphd-ogallala

[8301 rows x 15 columns]

In [2]:
###Task 1

##Group by location and calculate the mean and median concentrations of pollutants
stat_summary = air_data.groupby(['sensor.name']).agg(pm25_mean = ('pm2.5_atm', 'mean'),
                                                     pm25_median = ('pm2.5_atm', 'median'),
                                                     pm10_mean = ('pm10.0_atm', 'mean'),
                                                     pm10_median = ('pm10.0_atm', 'median'),
                                                     voc_mean = ('voc', 'mean'),
                                                     voc_median = ('voc', 'median')).round(2)

##Put in ascending order and display the top five values of each

#PM 2.5
top5_pm25_mean = stat_summary.sort_values(by='pm25_mean', ascending=False).head(5)
top5_pm25_median = stat_summary.sort_values(by='pm25_median', ascending=False).head(5)

#PM 10.0
top5_pm10_mean = stat_summary.sort_values(by='pm10_mean', ascending=False).head(5)
top5_pm10_median = stat_summary.sort_values(by='pm10_median', ascending=False).head(5)

#VOC
top5_voc_mean = stat_summary.sort_values(by='voc_mean', ascending=False).head(5)
top5_voc_median = stat_summary.sort_values(by='voc_median', ascending=False).head(5)

#Display the information
print("Top 5 PM 2.5 Locations by Mean")
display(top5_pm25_mean)

print("Top 5 PM 2.5 Locations by Median")
display(top5_pm25_median)

print("Top 5 PM 10.0 Locations by Mean")
display(top5_pm10_mean)

print("Top 5 PM 10.0 Locations by Median")
display(top5_pm10_median)

print("Top 5 VOC Locations by Mean")
display(top5_voc_mean)

print("Top 5 VOC Locations by Median")
display(top5_voc_median)

Top 5 PM 2.5 Locations by Mean

,pm25_mean,pm25_median,pm10_mean,pm10_median,voc_mean,voc_median
sensor.name,,,,,,
Broken Bow,928.71,36.05,929.68,43.18,158.29,138.56
#16 - Richardson County Courthouse,700.13,11.98,701.63,13.31,86.76,84.47
#18 - Southeast District Health Department- Tecumseh,613.18,10.32,614.23,11.43,196.15,138.58
NCDHD O'Neill #11,164.50,7.25,166.13,8.43,283.63,238.40
Swnphd-mccook,123.01,4.58,124.23,5.37,353.94,381.47

Top 5 PM 2.5 Locations by Median

,pm25_mean,pm25_median,pm10_mean,pm10_median,voc_mean,voc_median
sensor.name,,,,,,
Broken Bow,928.71,36.05,929.68,43.18,158.29,138.56
#16 - Richardson County Courthouse,700.13,11.98,701.63,13.31,86.76,84.47
#18 - Southeast District Health Department- Tecumseh,613.18,10.32,614.23,11.43,196.15,138.58
ELVPHD Norfolk HD 4,13.37,9.71,15.97,11.47,360.83,368.58
ELVPHD Wisner HD 5,11.15,8.46,14.46,10.94,102.29,100.71

Top 5 PM 10.0 Locations by Mean

,pm25_mean,pm25_median,pm10_mean,pm10_median,voc_mean,voc_median
sensor.name,,,,,,
Broken Bow,928.71,36.05,929.68,43.18,158.29,138.56
#16 - Richardson County Courthouse,700.13,11.98,701.63,13.31,86.76,84.47
#18 - Southeast District Health Department- Tecumseh,613.18,10.32,614.23,11.43,196.15,138.58
NCDHD O'Neill #11,164.50,7.25,166.13,8.43,283.63,238.40
Swnphd-mccook,123.01,4.58,124.23,5.37,353.94,381.47

Top 5 PM 10.0 Locations by Median

,pm25_mean,pm25_median,pm10_mean,pm10_median,voc_mean,voc_median
sensor.name,,,,,,
Broken Bow,928.71,36.05,929.68,43.18,158.29,138.56
#16 - Richardson County Courthouse,700.13,11.98,701.63,13.31,86.76,84.47
ELVPHD Norfolk HD 4,13.37,9.71,15.97,11.47,360.83,368.58
#18 - Southeast District Health Department- Tecumseh,613.18,10.32,614.23,11.43,196.15,138.58
ELVPHD Wisner HD 5,11.15,8.46,14.46,10.94,102.29,100.71

Top 5 VOC Locations by Mean

,pm25_mean,pm25_median,pm10_mean,pm10_median,voc_mean,voc_median
sensor.name,,,,,,
Swnphd-ogallala,10.40,3.52,11.35,4.15,399.43,423.08
FCHD-YPS,9.17,5.84,11.14,7.44,372.46,375.38
Three Rivers Public Health Department,9.60,6.86,11.23,8.24,370.22,376.81
ELVPHD Norfolk HD 4,13.37,9.71,15.97,11.47,360.83,368.58
Swnphd-mccook,123.01,4.58,124.23,5.37,353.94,381.47

Top 5 VOC Locations by Median

,pm25_mean,pm25_median,pm10_mean,pm10_median,voc_mean,voc_median
sensor.name,,,,,,
Swnphd-ogallala,10.40,3.52,11.35,4.15,399.43,423.08
Swnphd-mccook,123.01,4.58,124.23,5.37,353.94,381.47
Three Rivers Public Health Department,9.60,6.86,11.23,8.24,370.22,376.81
FCHD-YPS,9.17,5.84,11.14,7.44,372.46,375.38
ELVPHD Norfolk HD 4,13.37,9.71,15.97,11.47,360.83,368.58

In [3]:
###Task 2

#Get the max values of each pollutant
pm25_max_value = air_data.agg(pm25_max=('pm2.5_atm','max')).iloc[0,0]
pm10_max_value = air_data.agg(pm10_max=('pm10.0_atm','max')).iloc[0,0]
voc_max_value = air_data.agg(voc_max=('voc','max')).iloc[0,0]

#Filter to the rows where pollutant levels are at maximums
pm25_max_rows = air_data[air_data['pm2.5_atm'] == pm25_max_value]
pm10_max_rows = air_data[air_data['pm10.0_atm'] == pm10_max_value]
voc_max_rows = air_data[air_data['voc'] == voc_max_value]

#Display the PM 2.5 values
pm25_max_rows

,date,monitor_index,humidity,pressure,temperature,voc,analog_input,pm2.5_alt,pm1.0_atm,pm2.5_atm,pm10.0_atm,sensor.latitude,sensor.longitude,sensor.altitude,sensor.name
7561,02/18/25,195317,NaN,NaN,NaN,NaN,0.07,1.7125,3781.691896,3782.823313,3784.682542,40.0622,-95.6024,1023,#16 - Richardson County Courthouse

In [4]:
#Display the PM 10.0 values
pm10_max_rows

,date,monitor_index,humidity,pressure,temperature,voc,analog_input,pm2.5_alt,pm1.0_atm,pm2.5_atm,pm10.0_atm,sensor.latitude,sensor.longitude,sensor.altitude,sensor.name
7561,02/18/25,195317,NaN,NaN,NaN,NaN,0.07,1.7125,3781.691896,3782.823313,3784.682542,40.0622,-95.6024,1023,#16 - Richardson County Courthouse

In [5]:
#Display the VOC values
voc_max_rows

,date,monitor_index,humidity,pressure,temperature,voc,analog_input,pm2.5_alt,pm1.0_atm,pm2.5_atm,pm10.0_atm,sensor.latitude,sensor.longitude,sensor.altitude,sensor.name
2391,06/24/24,195541,9.883429,897.678857,116.455286,1209.931571,0.010429,1.642857,1.066643,1.408286,1.799071,41.128284,-101.72022,3220,Swnphd-ogallala

In [8]:
###Task 3

##Categorize temperatures
#Step 1 - Define a function that assigns temperature levels
def assign_temperature(temperature):
    if temperature < 32:
        return 'Below Freezing'
    elif 32 <= temperature <= 50:
        return 'Cool'
    elif 50 <= temperature <= 70:
        return 'Warm'
    else:
        return 'Hot'

#Step 2 - Apply the function to my data
air_data['temperature_level'] = air_data['temperature'].apply(assign_temperature)  
#the input to my assign_temperature function would be the data column temperature

air_data

##Categorize humidities
#Step 1 - Define a function that assigns humidity levels
def assign_humidity(humidity):
    if humidity < 50:
        return 'Low'
    elif 50 <= humidity <= 80:
        return 'High'
    else:
        return 'Very High'

#Step 2 - Apply the function to my data
air_data['humidity_level'] = air_data['humidity'].apply(assign_humidity)  
#the input to my assign_temperature function would be the data column temperature

air_data

##make two pivot tables with means, one will be hastagged because two can't display at once
temperature_stats = pd.pivot_table(air_data,index="temperature_level",values=["pm2.5_atm","pm10.0_atm","voc"],aggfunc=["mean"])

temperature_stats

                         mean
                   pm10.0_atm   pm2.5_atm         voc
temperature_level
Below Freezing     276.080794  273.698560  257.628626
Cool               143.074475  141.658843  285.435146
Hot                 71.821037   70.145543  282.145818
Warm                87.428866   86.506629  257.015827

In [9]:
###Task 3 Continued

#added a new code block here for the sole purpose of showing the humidity pivot table

humidity_stats = pd.pivot_table(air_data,index="humidity_level",values=["pm2.5_atm","pm10.0_atm","voc"],aggfunc=["mean"])

humidity_stats

                      mean
                pm10.0_atm   pm2.5_atm         voc
humidity_level
High             82.561133   80.874444  252.664069
Low              77.880520   76.513935  279.329347
Very High       536.520850  533.786399   19.395555

In [10]:
###Task 4
##PM 2.5
#Step 1 - Isolate unhealthy levels of PM 2.5 
unhealthy_pm25 = air_data[(air_data['pm2.5_atm']>=35.5) &
                          (air_data['pm2.5_atm']<=55.4)]

#Step 2 - sort by date, sensor name, and location
unhealthy_pm25_events = unhealthy_pm25[['date','sensor.name','pm2.5_atm','sensor.latitude','sensor.longitude']].sort_values('date')  

unhealthy_pm25_events.head(3)

,date,sensor.name,pm2.5_atm,sensor.latitude,sensor.longitude
6730,01/09/25,South Heartland District Health Dept. Superior...,39.975313,40.019714,-98.071840
6721,01/09/25,PHS Fairbury JCHL 13,41.249042,40.156180,-97.175354
6720,01/09/25,#17 - Otoe County,35.746292,40.676200,-95.858300

In [11]:
###Task 4 Continued

##PM 10.0
#Step 1 - Isolate unhealthy levels of PM 10.0, anything greater than 100
unhealthy_pm10 = air_data[(air_data['pm10.0_atm']>=155) &
                          (air_data['pm10.0_atm']<=254)]

#Step 2 - sort by date and sensor name
unhealthy_pm10_events = unhealthy_pm10[['date','sensor.name','pm10.0_atm','sensor.latitude','sensor.longitude']].sort_values('date')  

unhealthy_pm10_events

,date,sensor.name,pm10.0_atm,sensor.latitude,sensor.longitude
2144,06/14/24,Loup Basin Public Health Department,231.757021,41.779380,-99.13804
2443,06/27/24,Swnphd-Benklemen,188.977500,40.050922,-101.53357
6076,12/08/24,#16 - Richardson County Courthouse,200.798396,40.062200,-95.60240

In [9]:
###Task 5

#Find the mean values to make an assumption on impact
mean_values = pd.pivot_table(air_data,index='sensor.altitude',values=["pm2.5_atm","pm10.0_atm","voc"],aggfunc=['mean']).sort_index()

mean_values

                       mean
                 pm10.0_atm   pm2.5_atm         voc
sensor.altitude
1023             701.632446  700.127342   86.758650
1033              10.683828    9.482822  221.091595
1055              11.671141    9.755345  251.427296
1143             614.227248  613.175352  196.150771
1188              11.226492    9.601760  370.216208
1385              14.462116   11.154420  102.291126
1438              11.132398    9.405360  275.879657
1522              15.969341   13.369492  360.833744
1537              10.254001    8.635639  130.631408
1597               9.851113    8.851045  178.745074
1639              11.138241    9.167842  372.462720
1810               9.365581    8.041274  227.439379
1920               9.852555    8.915233  305.385314
1984               8.944145    7.927510  209.876608
1990             166.132578  164.495078  283.633000
2147               9.596038    8.479442  328.835391
2174              10.454420    8.561095  352.833902
2392              19.548148   18.080629  311.912841
2519              12.390708   10.697058  219.200274
2576             124.227336  123.011622  353.941581
2582             929.678512  928.710593  158.285807
2800               4.817597    3.971512  168.480056
2850               7.509269    6.219710  260.536134
3005               9.041440    7.501374  336.400969
3220              11.347889   10.396579  399.434240
3269               7.281414    6.329091  285.456355
3661               7.712941    6.658474  258.691175